INSERT INTO students(student_id, first_name, last_name, group_id) VALUES(1, 'Oliver', 'Smith', 1);
INSERT INTO students(student_id, first_name, last_name, group_id) VALUES(2, 'Jack', 'Jones', 2);
INSERT INTO students(student_id, first_name, last_name, group_id) VALUES(3, 'Harry', 'Williams', 3);
INSERT INTO students(student_id, first_name, last_name, group_id) VALUES(4, 'Jacob', 'Brown', 4);
INSERT INTO students(student_id, first_name, last_name, group_id) VALUES(5, 'Charlie', 'Taylor', 5);

INSERT INTO groups(group_id, group_name) VALUES(1, 'AA-11');
INSERT INTO groups(group_id, group_name) VALUES(2, 'AB-22');
INSERT INTO groups(group_id, group_name) VALUES(3, 'BA-31');
INSERT INTO groups(group_id, group_name) VALUES(4, 'AC-42');
INSERT INTO groups(group_id, group_name) VALUES(5, 'CB-52');
INSERT INTO groups(group_id, group_name) VALUES(6, 'CA-61');
INSERT INTO groups(group_id, group_name) VALUES(7, 'CC-72');
INSERT INTO groups(group_id, group_name) VALUES(8, 'BB-81');
INSERT INTO groups(group_id, group_name) VALUES(9, 'RR-92');
INSERT INTO groups(group_id, group_name) VALUES(10, 'ZA-88');

INSERT INTO courses(course_id, course_name, course_description) VALUES(1, 'Chemical and Physical Biology', 'Welcome faculty, students and parents. The Office of Science Education brings you resources for improving undergraduate science education at Harvard for both the Physical Sciences and the Life Sciences Concentration Cluster, under the support and direction of The Division of Science which fosters learning and collaboration cross disiplines. ');
INSERT INTO courses(course_id, course_name, course_description) VALUES(2, 'Environmental Science and Public Policy', 'The concentration in Environmental Science and Public Policy is designed to provide a multi-disciplinary introduction to current problems of the environment. It is founded on the premise that the ability to form rational judgments concerning many of the complex challenges confronting society today involving the environment requires both an understanding of the underlying scientific and technical issues and an appreciation for the relevant economic, political, legal, historical and ethical dimensions.');
INSERT INTO courses(course_id, course_name, course_description) VALUES(3, 'Folklore and Mythology', 'The concentration in Folklore and Mythology is a liberal education in itself, and although most graduates of the program go on to successful careers in medicine, law, business, journalism, and other pursuits, an unusually large number of our alumni and alumnae teach and conduct research in a variety of academic departments. This concentration focuses on the study of society, past or present, through its cultural documents and artifacts, and uses a variety of methodologies drawn from the humanities and social sciences. To concentrate on a society’s folklore and mythology (on sub-national as well as national levels) is to understand its traditional self-definition through its epics, ballads, folktales, legends, beliefs, and other cultural phenomena, including music, song, and dance, and studying a group’s folklore shows how it identifies itself in relation to other groups.');
INSERT INTO courses(course_id, course_name, course_description) VALUES(4, 'History and Literature', 'An honors concentration for Harvard undergraduates, History & Literature provides a structured, interdisciplinary education to ensure that students acquire knowledge of broad historical periods, major works, and key themes in their fields, as well as focused study of particular texts, events, authors, or themes according to students unique areas of interest. ');
INSERT INTO courses(course_id, course_name, course_description) VALUES(5, 'Neurobiology', 'Our mission to educate and train the next generation of neuroscientists is supported by graduate programs at Harvard including the Program in Neuroscience (PiN), the Biological and Biomedical Sciences program, and others.  Our faculty actively participate in teaching the PiN curriculum and mentor trainees in their labs.  We have a Neuro Postdoc Club that offers postdocs a way to meet postdocs in other labs through career development activities, social gatherings, and scientific presentations.');
INSERT INTO courses(course_id, course_name, course_description) VALUES(6, 'Study of Religion', 'Religion is a dynamic and powerful force in shaping cultures and complex civilizations, so understanding religion is critical for many areas of study from art, literature, and music to history, politics, and public health. Studying religion is exciting and demanding. The history of religions is global in scope and invites us to study the languages and cultures of the world. The currents of religion today are swift and often turbulent and require the very best analysis of scholars in the humanities and social sciences.');
INSERT INTO courses(course_id, course_name, course_description) VALUES(7, 'Social Studies', 'Social Studies is an interdisciplinary concentration in the social sciences at Harvard College. For more than five decades it has brought together outstanding teachers and intellectually engaged students who share not only a fascination with social science research and theory but also concerns about pressing social, political, and economic problems facing contemporary societies. Members of the Committee are united in their belief that rigorous social science inquiry must cross disciplinary boundaries and that it should be based on an understanding of classic and contemporary social theory and on an intimate knowledge of the history and culture of the places we study.');
INSERT INTO courses(course_id, course_name, course_description) VALUES(8, 'Special Concentrations', 'Special Concentrations is a unique program at Harvard College, in which a student may design his or her own concentration.  Students who have intellectual goals that cannot be accommodated within the existing concentration structure may apply for the opportunity to create their own course of study.  Special Concentrations is not for students who are unsure about what they wants to do, or who wish to circumvent departmental requirements.  Rather it is for students who know precisely what they want to study and who have, after thorough research, determined that this aim cannot be achieved within the confines of our regular concentrations, joint concentrations, concentration plus secondary, or series of research projects.  Special Concentrations offers students the opportunity to design their own program of concentration with the advice and consent of various members of the faculty and administration.');
INSERT INTO courses(course_id, course_name, course_description) VALUES(9, 'Studies of Women, Gender, and Sexuality', 'Harvard`s Committee on Degrees in Studies of Women, Gender, and Sexuality (WGS) brings together a wide range of academic fields in the humanities, social sciences, and sciences (including history, literature, visual studies, anthropology, sociology, ethnic studies, LGBT studies, political science, psychology, and biology, to name just a few). As an interdisciplinary field of study, WGS pays close attention to how social norms have changed over time and how they vary across cultures.');
INSERT INTO courses(course_id, course_name, course_description) VALUES(10, 'Theater, Dance & Media ', 'Theater, Dance & Media (TDM) combines the study of theater, dance, and media practices with the histories and theories of expressive and embodied culture. TDM’s mission responds to both the Report of the Task Force on the Arts’ demand “to make the arts an integral part of the cognitive life of the university,” as well as to the consistent appeal from students over many decades to have an interdisciplinary performing arts concentration. Drawing on the many resources already dedicated to the performing arts at the university, including the American Repertory Theater, the Harvard Theatre Collection of Houghton Library, the Office for the Arts, the Harvard Dance Center, the Harvard Music Department, and the Department of Art, Film, and Visual Studies, this new concentration offers students the opportunity to investigate the myriad ways that live and digital arts have been used to convey the breadth of stories about the human experience.');


